services:
  backend:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - mssql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;databaseName=requestManagementDB;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourStrong@Passw0rd
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.SQLServerDialect

  mssql:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    environment:
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=YourStrong@Passw0rd'
      - 'MSSQL_PID=Express'
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
